import Store from 'electron-store';
import type { User, Product, Category, Order } from './types';

const store = new Store({
  name: 'noxtiz-pos-data',
});

export function seedCoffeeShopData() {
  // Clear existing data (optional - comment out if you want to keep existing data)
  // store.clear();

  // Seed Categories
  const categories: Category[] = [
    { id: 'cat-coffee', name: 'Coffee', color: '#8B4513', icon: '☕' },
    { id: 'cat-espresso', name: 'Espresso', color: '#654321', icon: '☕' },
    { id: 'cat-latte', name: 'Latte & Cappuccino', color: '#D2B48C', icon: '🥛' },
    { id: 'cat-cold', name: 'Cold Drinks', color: '#87CEEB', icon: '🧊' },
    { id: 'cat-pastry', name: 'Pastries', color: '#FFD700', icon: '🥐' },
    { id: 'cat-snack', name: 'Snacks', color: '#FF6347', icon: '🍪' },
    { id: 'cat-dessert', name: 'Desserts', color: '#FF69B4', icon: '🍰' },
    { id: 'cat-other', name: 'Others', color: '#9370DB', icon: '🍵' },
  ];
  store.set('categories', categories);

  // Seed Products
  const products: Product[] = [
    // Coffee - Hot
    {
      id: 'prod-americano',
      name: 'Americano',
      description: 'Espresso dengan air panas',
      price: 25000,
      category: 'cat-coffee',
      stock: 100,
      barcode: 'COFFEE001',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-espresso',
      name: 'Espresso',
      description: 'Kopi espresso murni',
      price: 20000,
      category: 'cat-espresso',
      stock: 150,
      barcode: 'COFFEE002',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-doppio',
      name: 'Doppio',
      description: 'Double espresso shot',
      price: 25000,
      category: 'cat-espresso',
      stock: 120,
      barcode: 'COFFEE003',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-cappuccino',
      name: 'Cappuccino',
      description: 'Espresso dengan steamed milk dan foam',
      price: 30000,
      category: 'cat-latte',
      stock: 200,
      barcode: 'COFFEE004',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-latte',
      name: 'Caffe Latte',
      description: 'Espresso dengan steamed milk',
      price: 32000,
      category: 'cat-latte',
      stock: 180,
      barcode: 'COFFEE005',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-flat-white',
      name: 'Flat White',
      description: 'Espresso dengan microfoam milk',
      price: 33000,
      category: 'cat-latte',
      stock: 150,
      barcode: 'COFFEE006',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-macchiato',
      name: 'Macchiato',
      description: 'Espresso dengan sedikit foam',
      price: 28000,
      category: 'cat-latte',
      stock: 140,
      barcode: 'COFFEE007',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-mocha',
      name: 'Mocha',
      description: 'Espresso dengan coklat dan steamed milk',
      price: 35000,
      category: 'cat-latte',
      stock: 160,
      barcode: 'COFFEE008',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-vanilla-latte',
      name: 'Vanilla Latte',
      description: 'Latte dengan vanilla syrup',
      price: 36000,
      category: 'cat-latte',
      stock: 170,
      barcode: 'COFFEE009',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-caramel-latte',
      name: 'Caramel Latte',
      description: 'Latte dengan caramel syrup',
      price: 36000,
      category: 'cat-latte',
      stock: 165,
      barcode: 'COFFEE010',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-iced-americano',
      name: 'Iced Americano',
      description: 'Espresso dengan air dingin dan es',
      price: 27000,
      category: 'cat-cold',
      stock: 200,
      barcode: 'COFFEE011',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-iced-latte',
      name: 'Iced Latte',
      description: 'Latte dingin dengan es',
      price: 34000,
      category: 'cat-cold',
      stock: 190,
      barcode: 'COFFEE012',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-cold-brew',
      name: 'Cold Brew',
      description: 'Kopi yang diseduh dingin selama 12-24 jam',
      price: 30000,
      category: 'cat-cold',
      stock: 100,
      barcode: 'COFFEE013',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-frappuccino',
      name: 'Frappuccino',
      description: 'Blended coffee dengan es',
      price: 40000,
      category: 'cat-cold',
      stock: 150,
      barcode: 'COFFEE014',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-matcha-latte',
      name: 'Matcha Latte',
      description: 'Matcha dengan steamed milk',
      price: 35000,
      category: 'cat-other',
      stock: 120,
      barcode: 'COFFEE015',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-chai-latte',
      name: 'Chai Latte',
      description: 'Teh chai dengan steamed milk',
      price: 33000,
      category: 'cat-other',
      stock: 110,
      barcode: 'COFFEE016',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Pastries
    {
      id: 'prod-croissant',
      name: 'Croissant',
      description: 'Croissant klasik Prancis',
      price: 25000,
      category: 'cat-pastry',
      stock: 50,
      barcode: 'PASTRY001',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-chocolate-croissant',
      name: 'Chocolate Croissant',
      description: 'Croissant dengan isi coklat',
      price: 30000,
      category: 'cat-pastry',
      stock: 45,
      barcode: 'PASTRY002',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-donut',
      name: 'Donut',
      description: 'Donut dengan berbagai topping',
      price: 15000,
      category: 'cat-pastry',
      stock: 80,
      barcode: 'PASTRY003',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-muffin',
      name: 'Muffin',
      description: 'Muffin blueberry atau coklat',
      price: 20000,
      category: 'cat-pastry',
      stock: 60,
      barcode: 'PASTRY004',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-bagel',
      name: 'Bagel',
      description: 'Bagel dengan cream cheese',
      price: 22000,
      category: 'cat-pastry',
      stock: 40,
      barcode: 'PASTRY005',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-sandwich',
      name: 'Sandwich',
      description: 'Sandwich isi ayam atau tuna',
      price: 35000,
      category: 'cat-pastry',
      stock: 30,
      barcode: 'PASTRY006',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Snacks
    {
      id: 'prod-cookies',
      name: 'Cookies',
      description: 'Cookies coklat chip',
      price: 12000,
      category: 'cat-snack',
      stock: 100,
      barcode: 'SNACK001',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-brownie',
      name: 'Brownie',
      description: 'Brownie coklat fudge',
      price: 18000,
      category: 'cat-snack',
      stock: 70,
      barcode: 'SNACK002',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-cake-slice',
      name: 'Cake Slice',
      description: 'Potongan kue (cheesecake, red velvet, dll)',
      price: 25000,
      category: 'cat-dessert',
      stock: 50,
      barcode: 'DESSERT001',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-tiramisu',
      name: 'Tiramisu',
      description: 'Tiramisu klasik Italia',
      price: 35000,
      category: 'cat-dessert',
      stock: 40,
      barcode: 'DESSERT002',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-waffle',
      name: 'Waffle',
      description: 'Waffle dengan maple syrup',
      price: 30000,
      category: 'cat-dessert',
      stock: 35,
      barcode: 'DESSERT003',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];
  store.set('products', products);

  // Seed Users (keep admin, add more)
  const existingUsers = store.get('users', []) as User[];
  const newUsers: User[] = [
    {
      id: 'user-cashier1',
      username: 'cashier1',
      email: 'cashier1@coffeeshop.com',
      role: 'cashier',
      password: 'cashier1',
      permissions: ['/pos', '/products', '/inventory', '/tables', '/orders'],
      createdAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'user-cashier2',
      username: 'cashier2',
      email: 'cashier2@coffeeshop.com',
      role: 'cashier',
      password: 'cashier2',
      permissions: ['/pos', '/products', '/inventory', '/tables', '/orders'],
      createdAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'user-manager',
      username: 'manager',
      email: 'manager@coffeeshop.com',
      role: 'manager',
      password: 'manager',
      createdAt: new Date().toISOString(),
      isActive: true,
    },
  ];

  // Only add new users if they don't exist
  const allUsers = [...existingUsers];
  newUsers.forEach((newUser) => {
    if (!allUsers.find((u) => u.username === newUser.username)) {
      allUsers.push(newUser);
    }
  });
  store.set('users', allUsers);

  console.log('✅ Coffee Shop data seeded successfully!');
  console.log(`📦 ${products.length} products added`);
  console.log(`📁 ${categories.length} categories added`);
  console.log(`👥 ${allUsers.length} users total`);
}

